# Generated by Django 5.0.1 on 2024-01-31 02:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category_movie",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="slug",
        ),
    ]
