# Generated by Django 5.0.1 on 2024-02-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0002_remove_category_movie_slug_remove_movie_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.CharField(max_length=250),
        ),
    ]
